"""Generate sample PDF resume for demo purposes"""
import os
from fpdf import FPDF

output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "examples", "sample_resume.pdf")
os.makedirs(os.path.dirname(output_path), exist_ok=True)

pdf = FPDF()
pdf.add_page()
pdf.set_font("Helvetica", "B", 16)
pdf.cell(0, 10, "Personal Information", new_x="LMARGIN", new_y="NEXT", align="C")
pdf.set_font("Helvetica", "", 12)
pdf.cell(0, 10, "Name: Zhang San", new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 10, "Phone: 13800138000", new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 10, "Email: zhangsan@example.com", new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 10, "City: Beijing", new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Education", new_x="LMARGIN", new_y="NEXT")
pdf.set_font("Helvetica", "", 12)
pdf.cell(0, 10, "Peking University - CS - Master - 2024", new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 10, "Wuhan University - SE - Bachelor - 2021", new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Skills", new_x="LMARGIN", new_y="NEXT")
pdf.set_font("Helvetica", "", 12)
pdf.cell(0, 10, "Python, Go, React, PostgreSQL, Docker, K8s, ML, LLM", new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Experience", new_x="LMARGIN", new_y="NEXT")
pdf.set_font("Helvetica", "", 12)
pdf.multi_cell(0, 10, "Full-stack Developer at ABC Tech (2021-2024). Built web apps with React and Python.")
pdf.output(output_path)
print("Sample PDF generated:", output_path)
print("File size:", os.path.getsize(output_path))
